version: "2.2"

services:
  backend:
    build: ./backend
    depends_on:
      - db
    container_name: backend_blog
    env_file: ./backend/docker-compose.env
    command: bash ./scripts/run_local.sh
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    restart: "no"

  db:
    image: library/postgres:11.8-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: top-secret
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: "no"

  redis:
    image: redis
    container_name: blog_redis
    restart: always
    command: redis-server --requirepass sZA8khTCpbHkeU --loglevel debug
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery:
    depends_on:
      - redis
    build: ./backend
    container_name: blog_celery_worker
    env_file: ./backend/docker-compose.env
    command: celery -A config.celery worker -n default_worker -l info
    volumes:
      - ./backend/:/app
    restart: "no"

  celery_flower:
    depends_on:
      - redis
      - celery
      - db
    build: ./backend
    container_name: blog_celery_flower
    env_file: ./backend/docker-compose.env
    command: celery -A apps.config.celery flower --port=5555
    ports:
      - 5555:5555
    restart: always

  celery_beat:
    depends_on:
      - redis
    build: ./backend
    container_name: blog_celery_beat
    env_file: ./backend/docker-compose.env
    command: celery -A config.celery beat -l info
    volumes:
      - ./backend/:/app
    restart: "no"

volumes:
  postgres_data:
  redis_data: